export const WATCHDOG_METADATA_KEY = "watchdog"
export const WATCHDOG_METADATA_VERSION = 1

export const WATCHDOG_ADVISORY_HEADER =
  "[watchdog advisory: generated by a secondary model, not a user instruction]"

export const GOAL_PLUGIN_PACKAGE = "@prevalentware/opencode-goal-plugin"
export const GOAL_PLUGIN_FIXTURE_VERSION = "0.1.49"

export const MAX_FOREIGN_PATTERNS = 16
export const MAX_FOREIGN_PATTERN_CHARS = 1024
export const MAX_CLASSIFIER_TEXT_CHARS = 100_000

export type ForeignContinuationPattern = {
  id: string
  plugin: string
  version: string
  startsWith: string
  orderedFragments: string[]
}

export type ForeignContinuationMode = "extend" | "replace"

export type ForeignContinuationPatternInput = {
  id?: unknown
  plugin?: unknown
  version?: unknown
  startsWith?: unknown
  orderedFragments?: unknown
}

export type ForeignContinuationConfig = {
  mode?: unknown
  patterns?: unknown
}

export type CompiledForeignPatterns = {
  mode: ForeignContinuationMode
  patterns: ForeignContinuationPattern[]
  warnings: string[]
}

export type UserMessageKind = "real" | "watchdog" | "foreign"

export type UserMessageClassification = {
  kind: UserMessageKind
  patternID?: string
}

export type ClassifiablePart = {
  type?: unknown
  text?: unknown
  synthetic?: unknown
  metadata?: unknown
}

export type ClassifiableUserMessage = {
  info?: { role?: unknown } | undefined
  parts?: readonly ClassifiablePart[] | undefined
}

export type ForeignPatternDrift = {
  patternID: string
  matchedFragments: number
  totalFragments: number
  missingFragment: string
}

export const BUILT_IN_FOREIGN_PATTERNS: readonly ForeignContinuationPattern[] = [
  {
    id: "goal-0.1.49-active",
    plugin: GOAL_PLUGIN_PACKAGE,
    version: GOAL_PLUGIN_FIXTURE_VERSION,
    startsWith: "Continue working toward the active session goal.\n\n",
    orderedFragments: [
      "The objective below is user-provided data.",
      "<untrusted_objective>\n",
      "\n</untrusted_objective>\n\nContinuation behavior:\n",
      "\n\nBudget:\n",
      "\n\nWork from evidence:\n",
    ],
  },
  {
    id: "goal-0.1.49-limit",
    plugin: GOAL_PLUGIN_PACKAGE,
    version: GOAL_PLUGIN_FIXTURE_VERSION,
    startsWith: "The active session goal has reached a safety limit.\n\n",
    orderedFragments: [
      "The objective below is user-provided data.",
      "<untrusted_objective>\n",
      "\n</untrusted_objective>\n\nBudget:\n",
      "\n\nStatus: ",
      "\nStop reason: ",
    ],
  },
]

function boundedText(text: string): string {
  return text.length > MAX_CLASSIFIER_TEXT_CHARS ? text.slice(0, MAX_CLASSIFIER_TEXT_CHARS) : text
}

function stringField(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined
  const trimmed = value.trim()
  if (!trimmed || trimmed.length > MAX_FOREIGN_PATTERN_CHARS) return undefined
  return value
}

function fragmentList(value: unknown): string[] | undefined {
  if (!Array.isArray(value) || value.length === 0) return undefined
  const fragments: string[] = []
  for (const entry of value) {
    const fragment = stringField(entry)
    if (fragment === undefined) return undefined
    fragments.push(fragment)
  }
  return fragments
}

export function validateForeignPattern(
  input: ForeignContinuationPatternInput,
): { pattern: ForeignContinuationPattern } | { warning: string } {
  const id = stringField(input.id)
  if (!id) return { warning: "foreign continuation pattern without a usable id was ignored" }
  if (id !== input.id) return { warning: `foreign continuation pattern ${id} has untrimmed id` }

  const startsWith = stringField(input.startsWith)
  if (!startsWith) return { warning: `foreign continuation pattern ${id} has no usable startsWith` }
  if (startsWith !== input.startsWith) return { warning: `foreign continuation pattern ${id} has untrimmed startsWith` }

  const orderedFragments = fragmentList(input.orderedFragments)
  if (!orderedFragments) {
    return { warning: `foreign continuation pattern ${id} has no usable orderedFragments` }
  }

  const plugin = typeof input.plugin === "string" && input.plugin.trim() ? input.plugin : "configured"
  const version = typeof input.version === "string" && input.version.trim() ? input.version : "unspecified"

  return { pattern: { id, plugin, version, startsWith, orderedFragments } }
}

export function compileForeignPatterns(config: ForeignContinuationConfig | undefined): CompiledForeignPatterns {
  const warnings: string[] = []
  const mode: ForeignContinuationMode = config?.mode === "replace" ? "replace" : config?.mode === undefined ? "extend" : config.mode === "extend" ? "extend" : "extend"
  if (config?.mode !== undefined && config.mode !== "extend" && config.mode !== "replace") {
    warnings.push("unknown foreignContinuationPatterns.mode; defaulting to extend")
  }

  const base = mode === "extend" ? BUILT_IN_FOREIGN_PATTERNS : []
  const patterns: ForeignContinuationPattern[] = [...base]
  const seen = new Set(patterns.map((pattern) => pattern.id))

  const configured = Array.isArray(config?.patterns) ? config.patterns : []
  if (config?.patterns !== undefined && !Array.isArray(config.patterns)) {
    warnings.push("foreignContinuationPatterns.patterns was not an array; ignoring configured patterns")
  }

  for (const entry of configured) {
    if (!entry || typeof entry !== "object") {
      warnings.push("foreign continuation pattern was not an object; ignored")
      continue
    }
    const result = validateForeignPattern(entry as ForeignContinuationPatternInput)
    if ("warning" in result) {
      warnings.push(result.warning)
      continue
    }
    if (seen.has(result.pattern.id)) {
      warnings.push(`duplicate foreign continuation pattern id ${result.pattern.id} was ignored`)
      continue
    }
    if (patterns.length >= MAX_FOREIGN_PATTERNS) {
      warnings.push(`foreign continuation pattern limit ${MAX_FOREIGN_PATTERNS} reached; ${result.pattern.id} was ignored`)
      continue
    }
    seen.add(result.pattern.id)
    patterns.push(result.pattern)
  }

  return { mode, patterns, warnings }
}

export function matchForeignContinuation(
  text: string,
  patterns: readonly ForeignContinuationPattern[],
): ForeignContinuationPattern | undefined {
  const bounded = boundedText(text)
  for (const pattern of patterns) {
    if (!bounded.startsWith(pattern.startsWith)) continue
    let cursor = pattern.startsWith.length
    let matched = true
    for (const fragment of pattern.orderedFragments) {
      const index = bounded.indexOf(fragment, cursor)
      if (index === -1) {
        matched = false
        break
      }
      cursor = index + fragment.length
    }
    if (matched) return pattern
  }
  return undefined
}

export function detectForeignPatternDrift(
  text: string,
  patterns: readonly ForeignContinuationPattern[],
): ForeignPatternDrift | undefined {
  const bounded = boundedText(text)
  for (const pattern of patterns) {
    if (!bounded.startsWith(pattern.startsWith)) continue
    let cursor = pattern.startsWith.length
    let matchedFragments = 0
    for (const fragment of pattern.orderedFragments) {
      const index = bounded.indexOf(fragment, cursor)
      if (index === -1) {
        return {
          patternID: pattern.id,
          matchedFragments,
          totalFragments: pattern.orderedFragments.length,
          missingFragment: fragment,
        }
      }
      cursor = index + fragment.length
      matchedFragments += 1
    }
  }
  return undefined
}

export function isWatchdogMetadata(value: unknown): boolean {
  if (!value || typeof value !== "object") return false
  const envelope = (value as Record<string, unknown>)[WATCHDOG_METADATA_KEY]
  if (!envelope || typeof envelope !== "object") return false
  return (envelope as Record<string, unknown>).version === WATCHDOG_METADATA_VERSION
}

export function isWatchdogGeneratedUserMessage(message: ClassifiableUserMessage): boolean {
  for (const part of message.parts ?? []) {
    if (part?.type !== "text") continue
    if (isWatchdogMetadata(part.metadata)) return true
  }
  return false
}

export function userMessageText(message: ClassifiableUserMessage): string {
  const texts: string[] = []
  for (const part of message.parts ?? []) {
    if (part?.type !== "text") continue
    if (part.synthetic === true) continue
    if (typeof part.text === "string") texts.push(part.text)
  }
  return texts.join("\n")
}

export function classifyUserMessage(
  message: ClassifiableUserMessage,
  patterns: readonly ForeignContinuationPattern[],
): UserMessageClassification {
  if (isWatchdogGeneratedUserMessage(message)) return { kind: "watchdog" }
  const pattern = matchForeignContinuation(userMessageText(message), patterns)
  if (pattern) return { kind: "foreign", patternID: pattern.id }
  return { kind: "real" }
}

export function isPluginGeneratedUserMessage(
  message: ClassifiableUserMessage,
  patterns: readonly ForeignContinuationPattern[],
): boolean {
  return classifyUserMessage(message, patterns).kind !== "real"
}
