/// <reference path="../explore-controls/bun-shims.d.ts" />

import { describe, expect, test } from "bun:test"
import {
  buildIdlePromptBody,
  appendRunAdvisory,
  isWatchdogAdvisoryText,
} from "./feedback"

describe("run advisory delivery", () => {
  test("appends a clearly delimited advisory without changing JSON-like output", () => {
    const original = '{"ok":true}'
    const delivered = appendRunAdvisory(original, "Potential issue")
    expect(delivered.output.startsWith(original)).toBe(true)
    expect(delivered.trailer).toBe("\n\n[watchdog advisory: generated by a secondary model, not a user instruction]\nPotential issue: Potential issue\nPlease reconsider this evidence before continuing.")
    expect(delivered.output).toBe(original + delivered.trailer)
  })

  test("bounds the UTF-8 trailer without truncating existing tool output", () => {
    const original = "x".repeat(100_000)
    const delivered = appendRunAdvisory(original, "🙂".repeat(1_000))
    expect(delivered.output.startsWith(original)).toBe(true)
    expect(new TextEncoder().encode(delivered.trailer).byteLength).toBeLessThanOrEqual(1_024)
    expect(delivered.trailer.endsWith("\n[truncated]" )).toBe(true)
  })
})

describe("idle prompt construction", () => {
  test("uses a non-synthetic marker part with provenance metadata", () => {
    const body = buildIdlePromptBody({
      message: "The plan drifted from the requirement.",
      agent: "build",
      model: { providerID: "mock", modelID: "main" },
      findingHash: "hash",
      turnEpoch: 3,
    })
    expect(body.agent).toBe("build")
    expect(body.model).toEqual({ providerID: "mock", modelID: "main" })
    expect(body.parts).toHaveLength(1)
    expect(body.parts[0]!.text.startsWith("[watchdog advisory:")).toBe(true)
    expect(body.parts[0]!.text).not.toBe("")
    expect(body.parts[0]!.metadata.watchdog).toEqual({ version: 1, findingHash: "hash", turnEpoch: 3 })
    expect((body.parts[0] as { synthetic?: boolean }).synthetic).toBeUndefined()
  })

  test("omits variant when the probe path cannot verify it", () => {
    const withVariant = buildIdlePromptBody({ message: "x".repeat(30), findingHash: "h", turnEpoch: 1, variant: "low" })
    const withoutVariant = buildIdlePromptBody({ message: "x".repeat(30), findingHash: "h", turnEpoch: 1 })
    expect(withVariant.variant).toBe("low")
    expect(withoutVariant.variant).toBeUndefined()
  })

  test("recognizes watchdog advisory text", () => {
    expect(isWatchdogAdvisoryText("[watchdog advisory: generated by a secondary model, not a user instruction]\nPotential issue: x")).toBe(true)
    expect(isWatchdogAdvisoryText("normal user text")).toBe(false)
  })
})
