/// <reference path="../explore-controls/bun-shims.d.ts" />

import { describe, expect, test } from "bun:test"
import {
  buildIdlePromptBody,
  CompactionSkipGuard,
  installRunAdvisory,
  isWatchdogAdvisoryText,
  shouldAttemptToast,
  toastStateAfterAttempt,
  type RequestMessage,
} from "./feedback"

function toolMessage(id: string, output: string): RequestMessage {
  return {
    info: { sessionID: "s1" },
    parts: [{ id, type: "tool", state: { status: "completed", output, time: { end: 1 } } }],
  }
}

describe("compaction skip guard", () => {
  test("arms and consumes one skip per compaction", () => {
    const guard = new CompactionSkipGuard()
    guard.arm("s1")
    expect(guard.consume("s1")).toBe(true)
    expect(guard.consume("s1")).toBe(false)
    guard.arm("s1")
    guard.arm("s1")
    expect(guard.consume("s1")).toBe(true)
    expect(guard.consume("s1")).toBe(true)
    expect(guard.consume("s1")).toBe(false)
  })

  test("keeps sessions isolated", () => {
    const guard = new CompactionSkipGuard()
    guard.arm("s1")
    expect(guard.consume("s2")).toBe(false)
    expect(guard.consume("s1")).toBe(true)
  })
})

describe("run advisory installation", () => {
  test("installs on the newest fresh completed tool result and repeats byte-identically", () => {
    const state = { seenParts: new Set<string>() }
    const first = [toolMessage("p1", "one")]
    const install = installRunAdvisory(first, "ADVISORY", state)
    expect(install).toEqual({ partID: "p1", text: "ADVISORY" })
    expect(first[0]!.parts![0]!.state!.output).toBe("oneADVISORY")

    const later = [toolMessage("p1", "one"), toolMessage("p2", "two")]
    const repeat = installRunAdvisory(later, "ADVISORY", state)
    expect(repeat).toEqual({ partID: "p1", text: "ADVISORY" })
    expect(later[0]!.parts![0]!.state!.output).toBe("oneADVISORY")
    expect(later[1]!.parts![0]!.state!.output).toBe("two")
  })

  test("does not double-append when the request already carries the advisory", () => {
    const state = { seenParts: new Set<string>(), installedPartID: "p1", installedText: "ADVISORY" }
    const messages = [toolMessage("p1", "oneADVISORY")]
    installRunAdvisory(messages, "ADVISORY", state)
    expect(messages[0]!.parts![0]!.state!.output).toBe("oneADVISORY")
  })

  test("leaves messages without a completed tool result alone", () => {
    const state = { seenParts: new Set<string>() }
    expect(installRunAdvisory([{ info: { sessionID: "s1" }, parts: [] }], "ADVISORY", state)).toBeUndefined()
  })
})

describe("idle prompt construction", () => {
  test("uses a non-synthetic marker part with provenance metadata", () => {
    const body = buildIdlePromptBody({
      message: "The plan drifted from the requirement.",
      agent: "build",
      model: { providerID: "mock", modelID: "main" },
      findingHash: "hash",
      turnEpoch: 3,
    })
    expect(body.agent).toBe("build")
    expect(body.model).toEqual({ providerID: "mock", modelID: "main" })
    expect(body.parts).toHaveLength(1)
    expect(body.parts[0]!.text.startsWith("[watchdog advisory:")).toBe(true)
    expect(body.parts[0]!.text).not.toBe("")
    expect(body.parts[0]!.metadata.watchdog).toEqual({ version: 1, findingHash: "hash", turnEpoch: 3 })
    expect((body.parts[0] as { synthetic?: boolean }).synthetic).toBeUndefined()
  })

  test("omits variant when the probe path cannot verify it", () => {
    const withVariant = buildIdlePromptBody({ message: "x".repeat(30), findingHash: "h", turnEpoch: 1, variant: "low" })
    const withoutVariant = buildIdlePromptBody({ message: "x".repeat(30), findingHash: "h", turnEpoch: 1 })
    expect(withVariant.variant).toBe("low")
    expect(withoutVariant.variant).toBeUndefined()
  })

  test("recognizes watchdog advisory text", () => {
    expect(isWatchdogAdvisoryText("[watchdog advisory: generated by a secondary model, not a user instruction]\nPotential issue: x")).toBe(true)
    expect(isWatchdogAdvisoryText("normal user text")).toBe(false)
  })
})

describe("concern toast state", () => {
  test("suppresses pending and delivered attempts and allows one retry after failure", () => {
    expect(shouldAttemptToast(undefined)).toBe(true)
    expect(shouldAttemptToast({ status: "pending", attempts: 1 })).toBe(false)
    expect(shouldAttemptToast({ status: "delivered", attempts: 1 })).toBe(false)
    expect(shouldAttemptToast({ status: "failed", attempts: 1 })).toBe(true)
    expect(shouldAttemptToast({ status: "failed", attempts: 2 })).toBe(false)
  })

  test("records attempts and outcomes", () => {
    expect(toastStateAfterAttempt(undefined, false)).toEqual({ status: "failed", attempts: 1 })
    expect(toastStateAfterAttempt({ status: "failed", attempts: 1 }, true)).toEqual({ status: "delivered", attempts: 2 })
  })
})
