#!/usr/bin/env bash

# Get the name of the current branch
current_branch=$(git rev-parse --abbrev-ref HEAD)

# Perform git diff between the local branch and its remote counterpart
echo -e "Comparing ${current_branch} to origin/${current_branch}:\n\n"
git diff "origin/${current_branch}" $@
