#!/usr/bin/env bash

# Set a default remote name
default_remote="origin"

# Check if a remote name is passed as an argument
remote_name=${1:-$default_remote}

# Get the name of the current branch
current_branch=$(git rev-parse --abbrev-ref HEAD)

# Perform git diff between the local branch and its remote counterpart
clear
git diff "${remote_name}/${current_branch}"
