#!/usr/bin/env bash

message='WIP'

if [ ! -z ${1} ]; then message="WIP $*"; fi

git add . && git commit -m "${message}" --no-verify 
if [ $? -eq 0 ]; then
    if [ $(git remote | wc -l) != "0" ]; then
        git push origin
    fi
fi

